ci update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,6 +58,13 @@ jobs:
         else
           echo -e "Execution Fail!"
           exit 1
+        fi        resp=$(curl http://localhost:8001/bob -X POST -d "12345")
+        echo "$resp"
+        if [[ $resp == "0.08" ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
         fi
         kill -9 `cat wasmedge.pid`
         rm wasmedge.pid
